name: Test PAT

on:
  push:
    branches:
      - main

jobs:
  test-pat:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Test PAT
        run: |
          echo "Testing PAT..."
          latest_release=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
          echo "Latest release is $latest_release"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
